export { HomeFeatures } from './HomeFeatures'
export { HomeHero } from './HomeHero'
export { CallToAction } from './CallToAction'
export { FeatureDetails } from './FeatureDetails'
export { Newsletter } from './Newsletter'
export { NFTCollections } from './NFTCollections'
export { NFTPlatform } from './NFTPlatform'
